Added JSTL url in signupCheck.jsp page to use the ForLoop and many more JSTL features. Changed hobby from String to String array in SiginUpInfoDTO for getting the array of all the selected values. Added new 3 Dependencies for the working of this JSTL link (<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c" %>) inside signupCheck.jsp. This dependencies are  Primary dependency is jstl and remaining 2 dependencies are added because we are facing issue like NoClassDefFoundError so to over come from that we added jakarta.servlet.jsp.jstl and jakarta.servlet.jsp.jstl-api.